//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEscritorio.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbhelpdeskEntities : DbContext
    {
        public dbhelpdeskEntities()
            : base("name=dbhelpdeskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ViewUsuario> ViewUsuarios { get; set; }
        public virtual DbSet<VistaEventosCerrado> VistaEventosCerrados { get; set; }
        public virtual DbSet<VistaEventosSinCerrar> VistaEventosSinCerrars { get; set; }
        public virtual DbSet<VistaIncidentesCerrado> VistaIncidentesCerrados { get; set; }
        public virtual DbSet<VistaIncidentesSinCerrar> VistaIncidentesSinCerrars { get; set; }
    }
}
