//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEscritorio.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbhelpdeskV2Entities : DbContext
    {
        public dbhelpdeskV2Entities()
            : base("name=dbhelpdeskV2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vt_equipos> vt_equipos { get; set; }
        public virtual DbSet<vt_evento_sin_cerrar> vt_evento_sin_cerrar { get; set; }
        public virtual DbSet<vt_incidente_sin_cerrar> vt_incidente_sin_cerrar { get; set; }
        public virtual DbSet<vt_usuarios> vt_usuarios { get; set; }
    }
}
